### ISSUE TITLE
Blacklist

### ISSUE THREAD

**Issue by ValheimReloaded** [MSchmoecker/VNEI#10]
I have a ton of items Id like to blacklist in VNEI for my modpack. Is it possible to do this?
Wouldn't there be possible to have a blacklist.json file and I just put the list of items in there?

**Comment by MSchmoecker** [comment]
Yes, this would be possible. I even have a json blacklist internally for a handful of item, exposing a second isn't an issue. Although, if you really have a ton of items it would be better to have an automated system for those.
Are the items you mean real items, e.g. craftables, drops or non real ones, e.g.  attacks?

**Comment by MSchmoecker** [comment]
This is now implemented in the new release (0.7.0), see [here](https://github.com/MSchmoecker/VNEI#item-blacklist) for instruction. I decided against json and just did it with plain text on every line as there is no need for such overhead for a simple list.
