### ISSUE TITLE
[Bug Report] VNEI 0.8.0 - Jotun Puffs and Magecap appear in VNEI regardless of settings or discovery

### ISSUE THREAD

**Issue by Abbanon** [MSchmoecker/VNEI#12]
As the report title says, `Jotun Puffs` and `Magecap` appear in the VNEI tab - Before you discover them in-game, and with Show Only Known enabled.

Here's a screenshot with a brand new save:
![892970_20230112142503_1](https://user-images.githubusercontent.com/37251822/212162778-fbc847e1-60ba-4305-8b4a-4bb38632bab9.png)

**Comment by MSchmoecker** [comment]
Thanks for the report, I will look at the Problem soon.

**Comment by MSchmoecker** [comment]
Fixed in 0.8.1
