### ISSUE TITLE
Request: Ability to blacklist planned items

### ISSUE THREAD

**Issue by MissingL-tter** [MSchmoecker/VNEI#13]
PlanBuild adds "planned" pieces to the game. It looks like the piece names are suffixed with `_planned`.

Is there any way we can blacklist all of these?
Or add the ability to use a wildcard in the blacklist.txt (`*_planned`)

**Comment by MSchmoecker** [comment]
Good suggestion to disable the PlanBuild pieces, they are really cluttering without any real benefit.

This is now added in the latest VNEI update (0.8.3).

For the blacklist, I'm against wildcards as it only makes the detection code more complex which I'm trying to avoid. Wildcards also may unnoticeable disables items when not used carefully.
So I'd say it's better do to this in code, like now, where it can be more granular filtered then just by name.

**Comment by MissingL-tter** [comment]
Makes sense to me! I appreciate the fast response on this.
We just started using VNEI on our server and love it, thanks mate
