### ISSUE TITLE
Searching causes errors and sometimes crashes client

### ISSUE THREAD

**Issue by eviltek2099** [MSchmoecker/VNEI#21]
When using search it causes a lot of errors in the log.

> [Error  : Unity Log] ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: chunkLength
Stack trace:
System.Text.StringBuilder.ToString () (at <17d9ce77f27a4bd2afb5ba32c9bea976>:0)
Localization.Localize (System.String text) (at <fbcf12631bce4b62be6026f3e42ff0df>:0)
VNEI.UI.SearchUI.CalculateActive (VNEI.Logic.Item item, System.Boolean useBlacklist, VNEI.UI.SearchKey[] searchKeys) (at <8b36574bdb724d398e134644499a6259>:0)
VNEI.UI.SearchUI+<>c__DisplayClass19_0.<RecalculateActive>b__1 (VNEI.UI.SearchUI+ListItem i) (at <8b36574bdb724d398e134644499a6259>:0)
System.Threading.Tasks.Parallel+<>c__DisplayClass33_0`2[TSource,TLocal].<ForEachWorker>b__0 (System.Int32 i) (at <17d9ce77f27a4bd2afb5ba32c9bea976>:0)
System.Threading.Tasks.Parallel+<>c__DisplayClass19_0`1[TLocal].<ForWorker>b__1 (System.Threading.Tasks.RangeWorker& currentWorker, System.Int32 timeout, System.Boolean& replicationDelegateYieldedBeforeCompletion) (at <17d9ce77f27a4bd2afb5ba32c9bea976>:0)
--- End of stack trace from previous location where exception was thrown ---
System.Threading.Tasks.Parallel+<>c__DisplayClass19_0`1[TLocal].<ForWorker>b__1 (System.Threading.Tasks.RangeWorker& currentWorker, System.Int32 timeout, System.Boolean& replicationDelegateYieldedBeforeCompletion) (at <17d9ce77f27a4bd2afb5ba32c9bea976>:0)
System.Threading.Tasks.TaskReplicator+Replica`1[TState].ExecuteAction (System.Boolean& yieldedBeforeCompletion) (at <17d9ce77f27a4bd2afb5ba32c9bea976>:0)
System.Threading.Tasks.TaskReplicator+Replica.Execute () (at <17d9ce77f27a4bd2afb5ba32c9bea976>:0)
Rethrow as AggregateException: One or more errors occurred. (Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: chunkLength) (Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: chunkLength) (Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: chunkLength) (Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: chunkLength) (Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: chunkLength)
System.Threading.Tasks.TaskReplicator.Run[TState] (System.Threading.Tasks.TaskReplicator+ReplicatableUserAction`1[TState] action, System.Threading.Tasks.ParallelOptions options, System.Boolean stopOnFirstFailure) (at <17d9ce77f27a4bd2afb5ba32c9bea976>:0)
System.Threading.Tasks.Parallel.ForWorker[TLocal] (System.Int32 fromInclusive, System.Int32 toExclusive, System.Threading.Tasks.ParallelOptions parallelOptions, System.Action`1[T] body, System.Action`2[T1,T2] bodyWithState, System.Func`4[T1,T2,T3,TResult] bodyWithLocal, System.Func`1[TResult] localInit, System.Action`1[T] localFinally) (at <17d9ce77f27a4bd2afb5ba32c9bea976>:0)
--- End of stack trace from previous location where exception was thrown ---
System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException (System.Collections.ICollection exceptions, System.Threading.CancellationToken cancelToken, System.Exception otherException) (at <17d9ce77f27a4bd2afb5ba32c9bea976>:0)
System.Threading.Tasks.Parallel.ForWorker[TLocal] (System.Int32 fromInclusive, System.Int32 toExclusive, System.Threading.Tasks.ParallelOptions parallelOptions, System.Action`1[T] body, System.Action`2[T1,T2] bodyWithState, System.Func`4[T1,T2,T3,TResult] bodyWithLocal, System.Func`1[TResult] localInit, System.Action`1[T] localFinally) (at <17d9ce77f27a4bd2afb5ba32c9bea976>:0)
System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal] (System.Collections.Generic.IList`1[T] list, System.Threading.Tasks.ParallelOptions parallelOptions, System.Action`1[T] body, System.Action`2[T1,T2] bodyWithState, System.Action`3[T1,T2,T3] bodyWithStateAndIndex, System.Func`4[T1,T2,T3,TResult] bodyWithStateAndLocal, System.Func`5[T1,T2,T3,T4,TResult] bodyWithEverything, System.Func`1[TResult] localInit, System.Action`1[T] localFinally) (at <17d9ce77f27a4bd2afb5ba32c9bea976>:0)
System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal] (System.Collections.Generic.IEnumerable`1[T] source, System.Threading.Tasks.ParallelOptions parallelOptions, System.Action`1[T] body, System.Action`2[T1,T2] bodyWithState, System.Action`3[T1,T2,T3] bodyWithStateAndIndex, System.Func`4[T1,T2,T3,TResult] bodyWithStateAndLocal, System.Func`5[T1,T2,T3,T4,TResult] bodyWithEverything, System.Func`1[TResult] localInit, System.Action`1[T] localFinally) (at <17d9ce77f27a4bd2afb5ba32c9bea976>:0)
System.Threading.Tasks.Parallel.ForEach[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Action`1[T] body) (at <17d9ce77f27a4bd2afb5ba32c9bea976>:0)
VNEI.UI.SearchUI.RecalculateActive () (at <8b36574bdb724d398e134644499a6259>:0)
VNEI.UI.SearchUI.UpdateSearch (System.Boolean recalculateActive) (at <8b36574bdb724d398e134644499a6259>:0)
VNEI.UI.SearchUI.<Init>b__17_0 (System.String _) (at <8b36574bdb724d398e134644499a6259>:0)
UnityEngine.Events.InvokableCall`1[T1].Invoke (T1 args0) (at <ab14d35a27c043688812ae199c64b5aa>:0)
UnityEngine.Events.UnityEvent`1[T0].Invoke (T0 arg0) (at <ab14d35a27c043688812ae199c64b5aa>:0)
UnityEngine.UI.InputField.SendOnValueChanged () (at <4043a6cf2c744415844c8ec0cca11c21>:0)
UnityEngine.UI.InputField.Insert (System.Char c) (at <4043a6cf2c744415844c8ec0cca11c21>:0)
UnityEngine.UI.InputField.Append (System.Char input) (at <4043a6cf2c744415844c8ec0cca11c21>:0)
UnityEngine.UI.InputField.KeyPressed (UnityEngine.Event evt) (at <4043a6cf2c744415844c8ec0cca11c21>:0)
UnityEngine.UI.InputField.OnUpdateSelected (UnityEngine.EventSystems.BaseEventData eventData) (at <4043a6cf2c744415844c8ec0cca11c21>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IUpdateSelectedHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <4043a6cf2c744415844c8ec0cca11c21>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <4043a6cf2c744415844c8ec0cca11c21>:0)
UnityEngine.EventSystems.EventSystem:Update()

Running Ashland preview exe version 2022.3.17f1 (4#fc78088f837)

**Comment by MSchmoecker** [comment]
Fixed in 0.15.2
