### ISSUE TITLE
MissingMethodException

### ISSUE THREAD

**Issue by Dash200017** [MSchmoecker/VNEI#22]
[Info   : Unity Log] 05/20/2024 12:31:02: Setting selected recipe -1

[Error  : Unity Log] MissingMethodException: Method not found: string .DamageTypes.DamageRange(single,single,single)
Stack trace:
(wrapper dynamic-method) HitData+DamageTypes.DMD<HitData+DamageTypes::GetTooltipString>(HitData/DamageTypes&,Skills/SkillType)
(wrapper dynamic-method) ItemDrop+ItemData.DMD<ItemDrop+ItemData::GetTooltip>(ItemDrop/ItemData,int,bool,single)
VNEI.Logic.Item.GenerateTooltip (System.Int32 quality) (at <c8c70dc459854ba3a154708ffc8156f7>:0)
VNEI.Logic.Item.GetTooltip (System.Int32 quality) (at <c8c70dc459854ba3a154708ffc8156f7>:0)
VNEI.UI.DisplayItem.UpdateIconAndTooltip () (at <c8c70dc459854ba3a154708ffc8156f7>:0)
VNEI.UI.DisplayItem.SetItem (VNEI.Logic.Item target, System.Int32 quality) (at <c8c70dc459854ba3a154708ffc8156f7>:0)
VNEI.UI.SearchUI.UpdateSearch (System.Boolean recalculateActive) (at <c8c70dc459854ba3a154708ffc8156f7>:0)
VNEI.UI.SearchUI.LastPage () (at <c8c70dc459854ba3a154708ffc8156f7>:0)
UnityEngine.Events.InvokableCall.Invoke () (at <ab14d35a27c043688812ae199c64b5aa>:0)
UnityEngine.Events.UnityEvent.Invoke () (at <ab14d35a27c043688812ae199c64b5aa>:0)
UnityEngine.UI.Button.Press () (at <4043a6cf2c744415844c8ec0cca11c21>:0)
(wrapper dynamic-method) UnityEngine.UI.Button.DMD<UnityEngine.UI.Button::OnPointerClick>(UnityEngine.UI.Button,UnityEngine.EventSystems.PointerEventData)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <4043a6cf2c744415844c8ec0cca11c21>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <4043a6cf2c744415844c8ec0cca11c21>:0)
UnityEngine.EventSystems.EventSystem:Update()

**Comment by MSchmoecker** [comment]
This is an issue with another mod not updated for Ashlands, here VNEI only calls the vanilla method to generate a tooltip.
Meaning if you look at the tooltip without VNEI, you will get the same error.
