### ISSUE TITLE
Mark and print?

### ISSUE THREAD

**Issue by Sketaful** [MSchmoecker/VNEI#25]
I know this might fall outside of the scope of this mod (which I find is working perfectly), but would it be possible to add a way to print out the info? I would love that, either a way to mark multiple things and press something to print it out in a text file or like just rightclick and print one at a time.

I'm mainly using this to find out what other mods add to the game and what they're named so I can turn off the extra "crap" not needed with Wackys Database. :) (also noticed that changed recipes through wacky's actually show in this mod which is nice)

**Comment by MSchmoecker** [comment]
Have you looked at the commands https://github.com/MSchmoecker/VNEI?tab=readme-ov-file#ingame-commands to export item ids with context? Or do you mean something different?

**Comment by Sketaful** [comment]
Oh, that might do it. Missed that. :)
