### ISSUE TITLE
[ENHANCEMENT] Search as you type

### ISSUE THREAD

**Issue by sirskunkalot** [MSchmoecker/VNEI#5]
Would feel more intuitive, i guess.

Maybe I can get to some PR. But my list on Jötunn is long, too :P

**Comment by MSchmoecker** [comment]
Doesn't this already work? When I type something in the search bar, the available icons are getting updated. Or do you mean something different?

**Comment by sirskunkalot** [comment]
Whoops, my bad. Dunno why I was convinced that "Show search" executes the search and not the typing. Closing this...
