### ISSUE TITLE
Incompatibility - Valheim+

### ISSUE THREAD

**Issue by BlueberryWizard** [MSchmoecker/VNEI#6]
won't show itself with Valheim+ installed.

**Comment by MSchmoecker** [comment]
Tanks for the report. However I am not able to reproduce it with a clean V+ install where all configs are enabled. The VNEI GUI is visible for me. Could you share your logfile (`BepInEx/LogOutput.log`) and V+ config (`BepInEx/config/valheim_plus.cfg`) so I can track the issue down?

**Comment by BlueberryWizard** [comment]
[LogOutput.log](https://github.com/MSchmoecker/VNEI/files/7191671/LogOutput.log)
[valheim_plus.txt](https://github.com/MSchmoecker/VNEI/files/7191677/valheim_plus.txt)  <- CFG

**Comment by MSchmoecker** [comment]
You have an old BepInEx version, 5.4.11 not 5.4.15, this doesn't work with the latest Valheim version. Also VNEI isn't installed

**Comment by BlueberryWizard** [comment]
well, there you go, i'm the dumbass, well, in all but one, i did have it installed, log should have showed it, vortex says it's Enabled, altough i did disable it yesterday and play a bit before trying to see what might be wrong with it, and finally posting here, should have looked deeper, my bad.

**Comment by MSchmoecker** [comment]
Vortex is weird for Valheim, you have to press a button like 'Elevate' or so to apply the mods really. And Jotunn needs to be installed too, if that isn't the case already

**Comment by BlueberryWizard** [comment]
yeah, i did follow the instructions, just failed to see the update in BepX
