### ISSUE TITLE
[FEATURE] Display mod and prefab name

### ISSUE THREAD

**Issue by sirskunkalot** [MSchmoecker/VNEI#7]
For debugging and informational purposes ;)

**Comment by MSchmoecker** [comment]
Localized name, internal perfab name and mod name (if it is a Jotunn mod) are already shown. Here is an example of a Valharvest item:

![grafik](https://user-images.githubusercontent.com/39767545/141496069-4bfd6545-b62f-4c79-a278-ba45a2b55acf.png)

**Comment by sirskunkalot** [comment]
Sorry, too blind, i guess :)
