### ISSUE TITLE
Using VNEI with EpicLoot sacrifice tab in conflict

### ISSUE THREAD

**Issue by FelixReuthlinger** [MSchmoecker/VNEI#9]
I was just using VNEI in a mod setup together with EpicLoot. When sacrificing items from EL, I in parallel created a Wolf Armor Chest and upgraded it to max, which sounds weird, since those actions would come from 2 different tabs.

**Comment by MSchmoecker** [comment]
Thanks, I have reproduced this, you have to click twice to a EpicLoot tab to really switch. I think I found the error and can fix it, just have to verify that this doesn't have broken anything else. There are so may edge cases with many different mods in the tab system, it is really annoing
